#!/usr/bin/env python3
"""Freeze AgentLAB's checked-in 303-pair saved-attack transfer set."""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "runs/e79_external_benchmarks/AgentLAB/Task-Injection/agentdojo/res/long_horizon/gpt-4o-backip"
OUTPUT = ROOT / "evaluation/e79_long_horizon"
REPORTS = ROOT / "analysis/results"
REVISION = "36f58e60c36bbd6d5b8e61d50d7db7d9ea7258d7"
EXPECTED = {"workspace": 49, "travel": 25, "banking": 144, "slack": 85}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_rows() -> list[dict[str, Any]]:
    rows = []
    pattern = re.compile(r"^(user_task_\d+)_+(injection_task_\d+)$")
    for suite, expected in EXPECTED.items():
        suite_root = SOURCE_ROOT / suite / "v1.2.1"
        pair_dirs = sorted(path for path in suite_root.iterdir() if path.is_dir())
        if len(pair_dirs) != expected:
            raise RuntimeError(f"{suite}: expected {expected} pair directories, found {len(pair_dirs)}")
        for pair_dir in pair_dirs:
            match = pattern.match(pair_dir.name)
            if not match:
                raise RuntimeError(f"unrecognized pair directory: {pair_dir}")
            attack_path = pair_dir / "newest_injection.json"
            if not attack_path.exists():
                raise FileNotFoundError(attack_path)
            payload = json.loads(attack_path.read_text(encoding="utf-8"))
            if not isinstance(payload, list) or not payload:
                raise ValueError(f"empty or malformed saved attack: {attack_path}")
            content_blocks = sum(
                len(item.get("content", [])) for item in payload if isinstance(item, dict)
            )
            rows.append({
                "case_id": f"agentlab-saved::{suite}::{match.group(1)}::{match.group(2)}",
                "suite": suite,
                "user_task_id": match.group(1),
                "injection_task_id": match.group(2),
                "saved_attack_path": str(attack_path.relative_to(ROOT)),
                "saved_attack_sha256": sha256(attack_path),
                "n_injected_environment_records": len(payload),
                "n_message_blocks": content_blocks,
                "deployable_view": "original task and saved injected environment records; no evaluator outputs",
            })
    return sorted(rows, key=lambda row: row["case_id"])


def main() -> int:
    rows = build_rows()
    counts = Counter(row["suite"] for row in rows)
    canonical = json.dumps(rows, sort_keys=True, separators=(",", ":"))
    leakage_tokens = ("security_passed", "utility_passed", "expected_decision", "gold_atoms", "violation_reason")
    leakage = [
        {"case_id": row["case_id"], "token": token}
        for row in rows
        for token in leakage_tokens
        if token in Path(ROOT / row["saved_attack_path"]).read_text(encoding="utf-8")
    ]
    manifest = {
        "experiment": "E79",
        "dataset_id": "agentlab_task_injection_saved_transfer_303_v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "frozen_saved_attack_transfer_set" if len(rows) == 303 and not leakage else "failed",
        "source": {
            "repository": "https://github.com/TanqiuJiang/AgentLAB",
            "revision": REVISION,
            "artifact_subtree": str(SOURCE_ROOT.relative_to(ROOT)),
            "source_model_directory": "gpt-4o-backip",
        },
        "n_cases": len(rows),
        "suite_counts": dict(sorted(counts.items())),
        "manifest_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
        "leakage_scan": {"tokens": list(leakage_tokens), "violations": leakage, "n_violations": len(leakage)},
        "labels_and_scoring": (
            "User utility and attack success are computed later by the vendored deterministic AgentDojo v1.2.1 task predicates; "
            "no stored result boolean is part of this manifest or deployable input."
        ),
        "claim_boundary": (
            "These are 303 public saved attacks generated by the AgentLAB artifact and transferred unchanged to future victims. "
            "They are not generated adaptively against this paper's method, and this manifest contains no victim result."
        ),
        "cases_path": "evaluation/e79_long_horizon/agentlab_saved_attack_cases.jsonl",
    }
    OUTPUT.mkdir(parents=True, exist_ok=True)
    REPORTS.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "agentlab_saved_attack_cases.jsonl").write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows), encoding="utf-8"
    )
    (OUTPUT / "agentlab_saved_attack_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    lines = [
        "# E79 AgentLAB Saved-Attack Transfer Manifest", "",
        f"Status: `{manifest['status']}`.", "",
        f"- Cases: `{manifest['n_cases']}` ({json.dumps(manifest['suite_counts'], sort_keys=True)}).",
        f"- Manifest hash: `{manifest['manifest_sha256']}`.",
        f"- Leakage violations: `{manifest['leakage_scan']['n_violations']}`.", "",
        "## Claim Boundary", "", manifest["claim_boundary"], "",
    ]
    (REPORTS / "e79_agentlab_saved_attack_manifest.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0 if manifest["status"] == "frozen_saved_attack_transfer_set" else 1


if __name__ == "__main__":
    raise SystemExit(main())
